//! Numerical alignment vs PyTorch reference (P0b scalar baseline).
//!
//! The reference vectors (`tests/fixtures/c1_v2/ref_single.json`) were
//! generated by running `c1/src/intent/model/dialogue_gate.py` +
//! `multi_feature_head.py` against the real `v2_granite_best.pt` checkpoint
//! (47 keys, no_reset=True, use_multi_feature=True) with torch.manual_seed(0).
//! This test loads the same .pt and compares Rust `C1V2Tracker::step` output
//! against the canonical torch output, asserting max_abs_diff < 1e-5.
//!
//! Skips if the .pt checkpoint is absent (CI without model cache); the
//! committed ref_single.json makes the expected vectors reproducible.
use gllm::C1V2Tracker;
use std::fs;

const PT_PATH: &str = "/home/putao/.cache/c1_v2/v2_granite_best.pt";
const REF_PATH: &str = "tests/fixtures/c1_v2/ref_single.json";

fn available() -> bool { std::path::Path::new(PT_PATH).exists() }

#[derive(serde::Deserialize)]
struct RefOut {
    turn_embed: Vec<f32>,
    h_prev: Vec<Vec<f32>>,
    h_next: Vec<Vec<f32>>,
    intent_logits: Vec<f32>,
    diff_logits: Vec<f32>,
}

fn load_ref() -> RefOut {
    let s = fs::read_to_string(REF_PATH).unwrap();
    serde_json::from_str(&s).unwrap()
}

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    a.iter().zip(b.iter()).map(|(x,y)| (x-y).abs()).fold(0.0_f32, f32::max)
}

#[test]
fn c1_v2_numerical_alignment_vs_torch() {
    if !available() { eprintln!("skipped: {PT_PATH} not present"); return; }
    let ref_out = load_ref();
    let tracker = C1V2Tracker::from_pt(PT_PATH).expect("load .pt");
    let r = tracker.step(&ref_out.turn_embed, &ref_out.h_prev).expect("step");
    let dh = ref_out.h_next.iter().zip(r.h_next.iter())
        .map(|(a,b)| max_abs_diff(a,b)).fold(0.0_f32, f32::max);
    let di = max_abs_diff(&ref_out.intent_logits, &r.intent_logits);
    let dd = max_abs_diff(&ref_out.diff_logits, &r.diff_logits);
    eprintln!("max|h_next| diff = {dh}");
    eprintln!("max|intent| diff = {di}");
    eprintln!("max|diff|   diff = {dd}");
    // Tolerance: f32 accumulator vs torch f32 — BCE-20260702-001 fix achieves
    // h_next 7e-7 / intent 1e-6 / diff 7e-7. Allow 1e-5 headroom for f32 sum order.
    assert!(dh < 1e-5, "h_next drift {dh} exceeds tolerance");
    assert!(di < 1e-5, "intent drift {di} exceeds tolerance");
    assert!(dd < 1e-5, "diff drift {dd} exceeds tolerance");
}
